"""planets

Revision ID: cc166e9a6bc1
Revises: 8cee747a8129
Create Date: 2025-10-07 21:43:53.428521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc166e9a6bc1'
down_revision = '8cee747a8129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appearances', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('affiliations', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('locations', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vehicles', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('weapons', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('species', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tool', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('tool')
        batch_op.drop_column('species')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('gender')
        batch_op.drop_column('weapons')
        batch_op.drop_column('vehicles')
        batch_op.drop_column('locations')
        batch_op.drop_column('affiliations')
        batch_op.drop_column('appearances')

    # ### end Alembic commands ###
